### ISSUE TITLE
Begin and End element for Continuous members

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom#1]
In this method a Continuous member is created. A continuous member consist out of two line segments and two elements, and one member. 

In the user interface of IDEA the member will have a Begin and an End. 

![beginEnd](https://user-images.githubusercontent.com/48355355/57681686-7aaa4e00-7630-11e9-9e31-8395289f74cb.PNG)

Is it possible to control which segment will become the Begin and which will become the End?

https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L147

https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L170

https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L178

**Comment by mpospisil** [comment]
There is the property 

_ConnectedMember.IsContinuous_

if you set it to true, you will be able to set loading in both ends

**Comment by BouwenmetStaal** [comment]
In the IOMGenerator this is done differently.

This method is used to create ended members.
https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L199

This method is used to create continuous members.
https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L147

Within the method for continuous members, how can you control which segment is the DM1/Begin and which one is DM1/End?
