### ISSUE TITLE
USEWIZARD issue

### ISSUE THREAD

**Issue by ckostop** [idea-statica/iom#11]
In version 9 the USEWIZARD worked fine with the following parameters

                    bool USEWIZARD = false;
                    bool WAITFOREXIT = true;
                    bool EXPORTALLLINEARCOMBINATION = true;
                    string DESIGNCODE = "ECEN";
                    //string DESIGNCODE = "AISC";
                    string tmp_Name = TXT_CONNECT_NAME.Text.Trim();
                    if (string.IsNullOrEmpty(tmp_Name))
                    {
                        tmp_Name = "Test1";
                    }
                    tmp_Name = tmp_Name + @".ideaCon";
                    string OUTPUTFILE = Program.Path_Name + @"\IDEA\" + tmp_Name; // @"C:\IdeaFile.ideaCon";
                                                                                  //MemoryStream importSettingsStream = null;
                                                                                  //string importSettingsText = string.Empty;
                    importSettingsText += "<?xml version=\"1.0\" encoding=\"utf-16\"?>";
                    importSettingsText += "<IdeaConImportSettings>";
                    importSettingsText += "<UseWizard>" + USEWIZARD.ToString().ToLower() + "</UseWizard>";
                    importSettingsText += "<OnePageWizard>true</OnePageWizard>";
                    importSettingsText += "<DefaultBoltAssembly>M12 4.6</DefaultBoltAssembly>";
                    importSettingsText += "<ExportAllLinearCombination>" + EXPORTALLLINEARCOMBINATION.ToString().ToLower() + "</ExportAllLinearCombination>";
                    importSettingsText += "<ConnectionFileName>" + OUTPUTFILE + "</ConnectionFileName>";
                    importSettingsText += "<WaitForExit>" + WAITFOREXIT.ToString().ToLower() + "</WaitForExit>";
                    importSettingsText += "<DesignCode>" + DESIGNCODE.ToString().ToUpper() + "</DesignCode>";
                    importSettingsText += "</IdeaConImportSettings>";

In Version 10 with the above parameters doesn't work. When i set the parameter
  bool USEWIZARD = true 
the program works but we want this parameter false

**Comment by tLuber72** [comment]
We tested it current version 10.1 and it is working.
Which version of IDEA StatiCa you use?
If you are using the latest version and it does not work, pease connect part of the code where you run the IDEA Connection .

**Comment by tLuber72** [comment]
Could you try version 10.1? It works fine for me.

**Comment by TekuSP** [comment]
Because inactivity from user, issue closed.
If problem is still there, you can reopen your issue any time.
