### ISSUE TITLE
.ini file for IOM_IDEAConnectionRunner

### ISSUE THREAD

**Issue by jurgstahl** [idea-statica/iom#13]
where can i find the information what commands i can put in the *.ini file off IOM_IDEAConnectionRunner.exe?
known
SETTINGS;NEWPROJECT
OUTPUTFILE;test.ideaCon
USEWIZARD;TRUE
WAITFOREXIT;FALSE
IOM;test.xml

What else?
SETTINGS;NEWFileStream
templateFileName;test.ideaCon
Is this possible?

**Comment by mpospisil** [comment]
IDEA StatiCa v20.0 has the new API - IOM_IDEAConnectionRunner is not supported
