### ISSUE TITLE
xml into IOM_IDEAConnectionRunner.exe

### ISSUE THREAD

**Issue by jurgstahl** [idea-statica/iom#14]
I can't read the added xml file in IOM_IDEAConnectionRunner.exe.
It gives an error on the "OpenModelContainer xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance""
statement. When I removed the OpenModelContainer then IDEA wil open the node.
At the end i remove 
  "OpenModelResult>
    "ResultOnMembers>
      "ResultOnMembers>
        "Members />
      "/ResultOnMembers>
    "/ResultOnMembers>
  "/OpenModelResult>
"/OpenModelContainer>
Why won't it work properly?
What is wrong?

[testTekla1.xml.txt](https://github.com/idea-statica/iom/files/3911407/testTekla1.xml.txt)

**Comment by mpospisil** [comment]
IDEA StatiCa v20.0 has the new API - IOM_IDEAConnectionRunner is not supported
