### ISSUE TITLE
Table unbalanced forces

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom#2]
Can the table of unbalanced forces also be used in the API?
![image](https://user-images.githubusercontent.com/48355355/58422762-b9f68700-8093-11e9-9452-080ad2ca7096.png)

**Comment by mpospisil** [comment]
It is not in our API. But if you take internal forces from a FE analysis - forces should be balanced. We will prepare a better sample.

**Comment by mpospisil** [comment]
There is the new example describing how to correctly create IOM for a steel frame. You can see ended and continuous members in the generated connection. Loads are in eqilibrium in this example.
I hope it will help you to create correct connection model from your application.
