### ISSUE TITLE
Connecting to a live instance of Idea StatiCa Connection

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom#20]
Is there a way to connect to a live instance of Idea StatiCa Connection and simply use code from the documentation to automate tasks? For example, could I open Idea StatiCa, write a program that attaches to the instance of the program, create a simple connection model, run the analysis and extract the results into an excel file?

I'm more familiar with the SAP2000/ETABS API and with that API, you can do exactly what I described above. However, when I go through some of the examples that are laid out in the GitHubs, it seems like you can only export a model as opposed to being able to work on it in real time.

**Comment by mpospisil** [comment]
You can not to attach ab existing process but you can create and control a new one.

https://idea-statica.github.io/iom-examples/iom-steel-connections/connection-app-automation.html

If you miss anything add it as enhancement and specify your usese - if more people needs we will add it to our development backlog
