### ISSUE TITLE
[QUESTION] Missing VB Project files

### ISSUE THREAD

**Issue by jurekos** [idea-statica/iom#29]
Hi,
is it possible to get sample files described as "Samples\AllSamples.sln" (VB) at site on github? [link](https://idea-statica.github.io/iom/samples/idea-connections/idea-connections.html)
I just can't find it anywhere and I want to use VB

**Comment by mpospisil** [comment]
We will not support VB. Microsoft has stopped its development.

**Comment by jurekos** [comment]
> We will not support VB. Microsoft has stopped its development.

Ok, not supported...
but maybe getting these sample files is possible?
or it is just not possible to connect with VB from  VS2015 + IOM from nuget package?
