### ISSUE TITLE
In the IOMGenerator this is done differently.

### ISSUE THREAD

**Issue by BouwenmetStaal** [idea-statica/iom#3]
In the IOMGenerator this is done differently.

This method is used to create ended members.
https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L199

This method is used to create continuous members.
https://github.com/idea-statica/iom/blob/9e13201a49a1e97bcd6d4a80a19a4abe3b955c52/Samples/IdeaConnection/Sources/ConnectionLinkTestApp/IOMGenerator2.cs#L147

Within the method for continuous members, how can you control which segment is the DM1/Begin and which one is DM1/End?

_Originally posted by @BouwenmetStaal in https://github.com/idea-statica/iom/issues/1#issuecomment-492597589_

**Comment by mpospisil** [comment]
We will make better samples - I suppose the next week.

**Comment by mpospisil** [comment]
There is the new example describing how to correctly create IOM for a steel frame. You can see ended and continuous members in the generated connection. Loads are in eqilibrium in this example.
I hope it will help you to create correct connection model from your application.

https://github.com/idea-statica/iom-examples
