### ISSUE TITLE
How to start IDEA from the open model code?

### ISSUE THREAD

**Issue by GRamsaroep** [idea-statica/iom#6]
Hi,

I am trying to make a couple of beams with nodes in the code and project it to IDEA. But i dont have a clue how to get the info in my code to IDEA and make the model in IDEA.

I have followed the example on GitHub, but the example misses a lot of references. Is there any better example step by step or with screenshots of the code to make the beams with nodes?

**Comment by mpospisil** [comment]
I am not sure what you need. There is [working example](https://github.com/idea-statica/iom-examples) how to create a project for ideaconnection app from IOM.
You can open generated project in ideaconnection.exe

**Comment by GRamsaroep** [comment]
Thank you for the link. :)
