### ISSUE TITLE
IDEA StatiCa  10.1 and  Visual Studio version 2015

### ISSUE THREAD

**Issue by ckostop** [idea-statica/iom#8]
In our effort to link our software with the new version of IDEA StatiCa  10.1, we downloaded the examples but  the compilation fails in Visual Studio version 2015 that we currently use.  It shows the following message:
“2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".”

The message means that we need the newer Visual Studio version 2017?

**Comment by dawiddyrcz** [comment]
I am not sure but you should try to open Visual Studio Installer (Menu Start > Visual Studio Installer) and install .net 4.5, .net 4.6, .net 4.7, .net 4.7.1, and .net 4.7.2 and newer versions if exsists.

**Comment by TekuSP** [comment]
Hi, we fixed this problem in commit: https://github.com/idea-statica/iom/commit/04d0afeb57fb480373a030d3a5a16ab20d1a2f30 

Please try it now and look at our requirements list.
